const translations = {
  en: {
    bar48batumi: `Bar 48 - Batumi`,
    bar48batumiphotos: `Photos - Bar 48 - Batumi`,
    bar48batumidrink: `Drinks - Bar 48 - Batumi`,
    bar48batumifood: `Food - Bar 48 - Batumi`,
    bar48: `Bar 48`,
    open: `Open from 00:30 to 06:00`,
    address: `<a href="https://www.google.com/maps/place/Bar+48/@41.6472818,41.6299166,17z/data=!4m6!3m5!1s0x4067877c6534400d:0x36e22db643766849!8m2!3d41.6474543!4d41.6323109!16s%2Fg%2F11rvh7wrxh" target="_blank">Batumi, 26 May Street, 27</a>`,
    telegram: `<a href="https://t.me/BAR48_Batumi" target="_blank">Telegram group</a>`,
    offer: `🎉 Special Offer: Beer Deposit!`,
    offer2: `<strong>5 beers — 20 ₾ </strong>(Valid for one work shift)<br><strong>12 beers — 50 ₾ </strong>(Valid for 14 days)<br><br>📲<i> Available exclusively to members of our <a href="https://t.me/BAR48_Batumi" target="_blank">Telegram</a> group.</i>`,
    welcome: `Welcome to our bar!`,
    great: `Great drinks and a rock-bar atmosphere await you here every evening. <b>"Feeling down? Have a drink!"</b> — That's our motto! Enjoy the moment and pleasant company!`,
    photos: `<a href="/photos" class="button">Bar through photos</a>`,
    drinks: `<a href="/drinks">Drinks</a>`,
    food: `<a href="/food">Food</a>`,
    homestylepork: `Homestyle's pork — 14 ₾`,
    beervodka: `Beer, vodka, gin, whiskey and cocktails to suit every taste. We have everything!<p>More than 60 types of syrups and liqueurs</p>`,
    beer: `Batumi beer (400 ml) — 7 ₾<p>Always fresh, excellent beer direct from Batumi brewery</p>`,
    fulldrinks: `<a href="/drinks" class="button">Full drinks menu</a>`,
    fullfood: `<a href="/food" class="button">Full food menu</a>`,
    getdirections: `Get Directions`,
    map: `<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3545.564730481724!2d41.63337243995288!3d41.64596064402859!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4067877c6534400d%3A0x36e22db643766849!2z0JHQsNGAIDQ4!5e0!3m2!1sen!2sge!4v1701516762082!5m2!1sen!2sge" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade" title="googlemaps" data-i18n="map"></iframe>`,
    pleaseleaveareview: `Please leave a review`,
    home: `<a href="../" class="button">Home</a>`,
    beer1: `Beer`,
    shots: `Shots`,
    smoothies: `Alcohol Smoothies`,
    cocktails: `Alcohol Cocktails`,
    tequilaboom: `<font size="3">Tequila boom (40 ml) — 8 ₾<p>Tequila, Sprite</p></font>`,
    boyarasky: `<font size="3">Boyarasky (40 ml) — 11 ₾<p>Grenadine syrup, vodka, tabasco</p></font>`,
    valentinka: `<font size="3">Valentinka (40 ml) — 11 ₾<p>Author’s shot</p></font>`,
    greenmexican: `<font size="3">Green mexican (40 ml) — 13 ₾<p>Melon liqueur, lemon juice, tequila</p></font>`,
    bitterpill: `<font size="3">Bitter pill (40 ml) — 13 ₾<p>Mango syrup, red vermouth, vodka</p></font>`,
    arabica: `<font size="3">Arabica (40 ml) — 13 ₾<p>Grenadine syrup, coffee liqueur, lemon juice, tequila</p></font>`,
    b52: `<font size="3">B-52 (40 ml) — 13 ₾<p>Kahlua liqueur, baileys liqueur, triple sec liqueur</p></font>`,
    b53: `<font size="3">B-53 (40 ml) — 13 ₾<p>Kahlua liqueur, baileys liqueur, absinthe 70%</p></font>`,
    jellyfish: `<font size="3">Jellyfish (40 ml) — 15 ₾<p>Malibu liqueur, triple sec liqueur, baileys liqueur, blue curacao liqueur</p></font>`,
    hiroshima: `<font size="3">Hiroshima (40 ml) — 15 ₾<p>Sambuka liqueur, Baileys liqueur, absinthe 70%, grenadine syrup</p></font>`,
    kamikadze: `<font size="3">Kamikadze (40 ml) — 15 ₾<p>Author’s shot</p></font>`,
    coldseabuckthorn: `<font size="3">Cold sea buckthorn (150 ml) — 12 ₾<p>Vodka, sea buckthorn puree, grenadine syrup, lemon juice, ice</p></font>`,
    applecherry: `<font size="3">Apple-cherry (150 ml) — 12 ₾<p>Vodka, cherry puree, apple juice, lemon juice, ice</p></font>`,
    blackmaple: `<font size="3">Black maple (150 ml) — 12 ₾<p>Vodka, blueberry puree, maple syrup, lemon juice, ice</p></font>`,
    mexicanlime: `<font size="3">Mexican lime (150 ml) — 17 ₾<p>Tequila, lime puree, lemon juice, ice</p></font>`,
    icemango: `<font size="3">Ice mango (150 ml) — 17 ₾<p>Tequila, mango puree, lychee syrup, lemon juice, ice</p></font>`,
    cloverclubsmoothies: `<font size="3">Clover club smoothies (150 ml) — 18 ₾<p>Gin, raspberry puree, lemon juice, ice</p></font>`,
    blueorange: `<font size="3">Blue orange (150 ml) — 18 ₾<p>Gin, lime puree, blue curacao syrup, lemon juice, ice</p></font>`,
    antimojito: `<font size="3">Anti mojito (150 ml) — 22 ₾<p>Rum, lime puree, lime-lemon syrup, mint, lemon juice, ice</p></font>`,
    knickerbockersmoothie: `<font size="3">Knickerbocker smoothie (150 ml) — 22 ₾<p>Rum, raspberry puree, orange syrup, lemon juice, ice</p></font>`,
    bluelagoon: `<font size="3">Blue lagoon (200 ml) — 16 ₾<p>Vodka, blue curacao liqueur, sprite, ice</p></font>`,
    whiterussian: `<font size="3">White russian (150 ml) — 17 ₾<p>Vodka, Kahlua liqueur, cream, ice</p></font>`,
    margarita: `<font size="3">Margarita (150 ml) — 17 ₾<p>Olmeca tequila, triple sec liqueur, sugar syrup, lemon juice</p></font>`,
    gintonic: `<font size="3">Gin tonic (200 ml) — 17 ₾<p>Gin, tonic, lemon juice, ice</p></font>`,
    tequilasunrise: `<font size="3">Tequila sunrise (200 ml) — 18 ₾<p>Olmeca tequila, orange juice, grenadine syrup, ice</p></font>`,
    irishcoffee: `<font size="3">Irish coffee (150 ml) — 18 ₾<p>Irish whiskey, sugar syrup, coffee, whipped cream</p></font>`,
    cloverclub: `<font size="3">Clover club (150 ml) — 18 ₾<p>Gin, raspberry syrup, lemon juice, egg white</p></font>`,
    whiskeysour: `<font size="3">Whiskey sour (150 ml) — 18 ₾<p>Jameson whiskey, sugar syrup, lemon juice, egg white, angostura, ice</p></font>`,
    bloodymary: `<font size="3">Bloody Mary (200 ml) — 18 ₾<p>Vodka, tomato juice, soy sauce, tabasco, Worcester, salt, pepper, ice</p></font>`,
    cubalibre: `<font size="3">Cuba-libre (200 ml) — 18 ₾<p>Rum, cola, lemon juice, lemon, ice</p></font>`,
    french75: `<font size="3">French 75 (150 ml) — 18 ₾<p>Gin, prosecco, sugar syrup, lemon juice</p></font>`,
    negroni: `<font size="3">Negroni (100 ml) — 19 ₾<p>Gin, Campari, martini rosso, orange zest</p></font>`,
    daiquiri: `<font size="3">Daiquiri (150 ml) — 19 ₾<p>White rum, sugar syrup, lemon juice, lemon</p></font>`,
    aperolspritz: `<font size="3">Aperol spritz (150 ml) — 19 ₾<p>Aperol, champagne, tonic, orange</p></font>`,
    maitai: `<font size="3">Mai-tai (200 ml) — 20 ₾<p>White rum, dark rum, triple sec liqueur, almond syrup, sugar syrup, lemon juice, ice</p></font>`,
    espressomartini: `<font size="3">Espresso martini (150 ml) — 20 ₾<p>Vodka, coffee liqueur, coffee, sugar syrup</p></font>`,
    sexonthebeach: `<font size="3">Sex on the beach (200 ml) — 20 ₾<p>Vodka, peach liqueur, cranberry syrup, pineapple juice, lemon juice, ice</p></font>`,
    boulevardier: `<font size="3">Boulevardier (150 ml) — 20 ₾<p>Whiskey, red vermouth, campari, orange zest, ice</p></font>`,
    pinacolada: `<font size="3">Pina-colada (250 ml) — 25 ₾<p>White rum, Malibu liqueur, pineapple juice, coconut syrup, cream, ice</p></font>`,
    mojito: `<font size="3">Mojito (250 ml) — 25 ₾<p>White rum, sprite, mojito syrup, lemon juice, mint, lemon, ice</p></font>`,
    longisland: `<font size="3">Long island (250 ml) — 25 ₾<p>Vodka, tequila, gin, rum, triple sec liqueur, lemon juice, cola / iced tea, ice</p></font>`,
    pizza: `Pizza`,
    Carnea: `<font size="3">Pizza Carnea — 40 ₾<p>Specialty tomato sauce, mozzarella cheese, ham, chicken fillet, raw smoked bacon, salami sausage, tomatoes, onions</p></font>`,
    Suprim: `<font size="3">Pizza Suprim — 32 ₾<p>Specialty tomato sauce, mozzarella cheese, pepperoni sausage, bell peppers, chicken fillet, onions, mushrooms, olives</p></font>`,
    Bolognese: `<font size="3">Pizza Bolognese — 31 ₾<p>Specialty tomato sauce, mozzarella cheese, bacon, minced meat, tomatoes, onions, herbs</p></font>`,
    Spicy: `<font size="3">Pizza Spicy — 31 ₾<p>Specialty tomato sauce, mozzarella cheese, dorblu cheese, beef tenderloin, bacon, mushrooms, hot chili peppers</p></font>`,
    ShrimpPizza: `<font size="3">Shrimp Pizza — 31 ₾<p>Cheese-garlic sauce, mozzarella cheese, shrimp, olives</p></font>`,
    Brooklyn: `<font size="3">Brooklyn Pizza — 33 ₾<p>Specialty tomato sauce, mozzarella, cooked sausage, salami sausage, pepperoni sausage, mushrooms, dill</p></font>`,
    Diablo: `<font size="3">Diablo pizza — 30 ₾<p>Specialty tomato sauce, mozzarella cheese, ham, pepperoni sausage, mushrooms, hot chili peppers</p></font>`,
    FourCheesePizza: `<font size="3">Four Cheese Pizza — 29 ₾<p>Specialty tomato sauce, mozzarella cheese, dorblu cheese, sulguni cheese, parmesan cheese</p></font>`,
    Rustic: `<font size="3">Rustic pizza — 32 ₾<p>Specialty tomato sauce, mozzarella cheese, beef tenderloin, gherkins, tomatoes, greens</p></font>`,
    Hunter: `<font size="3">Hunter's Pizza — 28 ₾<p>Specialty tomato sauce, mozzarella cheese, hunting sausages, mushrooms, bell peppers, onions, tomatoes, bacon, greens</p></font>`,
    Caesarpizza: `<font size="3">Caesar pizza — 28 ₾<p>Caesar sauce, mozzarella cheese, parmesan cheese, chicken, bacon, iceberg lettuce, cherry tomatoes, croutons</p></font>`,
    Pepperoni: `<font size="3">Pepperoni pizza — 28 ₾<p>Specialty tomato sauce, mozzarella cheese, pepperoni sausage, bell peppers, olives</p></font>`,
    Halal: `<font size="3">Halal pizza — 28 ₾<p>Specialty tomato sauce, mozzarella cheese, beef, smoked chicken, tomatoes, onions</p></font>`,
    Goodmorning: `<font size="3">Good morning pizza — 26 ₾<p>Specialty tomato sauce, mozzarella cheese, bacon, tomatoes, chicken eggs, herbs</p></font>`,
    Romana: `<font size="3">Pizza Romana — 26 ₾<p>Olive oil, mozzarella cheese, Roquefort cheese, pear</p></font>`,
    Carbonara: `<font size="3">Pizza Carbonara — 26 ₾<p>Specialty tomato sauce, mozzarella cheese, parmesan cheese, chicken egg, raw smoked bacon, lettuce, tomatoes</p></font>`,
    Cippolino: `<font size="3">Cippolino's Pizza — 27 ₾<p>Specialty tomato sauce, mozzarella cheese, chicken fillet, gherkins, red onion, basil, herbs</p></font>`,
    Julienne: `<font size="3">Julienne pizza — 28 ₾<p>Sour cream sauce, mozzarella cheese, chicken fillet, mushrooms, onions, greens</p></font>`,
    ClubPizza: `<font size="3">Pizza Club — 26 ₾<p>Specialty tomato sauce, mozzarella cheese, ham, tomatoes</p></font>`,
    Zeus: `<font size="3">Zeus Pizza — 24 ₾<p>Olive oil, mozzarella cheese, tomatoes, bell pepper, olives, cucumber, cottage cheese, red onion</p></font>`,
    Gallina: `<font size="3">Pizza Gallina — 26 ₾<p>Specialty tomato sauce, mozzarella cheese, chicken fillet</p></font>`,
    Mushroom: `<font size="3">Mushroom pizza — 24 ₾<p>White sauce, mozzarella cheese, mushrooms, onions, dill</p></font>`,
    TwoCheesePizza: `<font size="3">Two Cheese Pizza — 22 ₾<p>Specialty tomato sauce, mozzarella cheese, sulguni cheese</p></font>`,
    Americana: `<font size="3">Pizza Americana — 32 ₾<p>Specialty tomato sauce, mozzarella cheese, ham, pepperoni sausage, mushrooms</p></font>`,
    Hawaii: `<font size="3">Pizza Hawaii — 27 ₾<p>Specialty tomato sauce, mozzarella cheese, chicken fillet, pineapple</p></font>`,
    Margarita: `<font size="3">Pizza Margarita — 25 ₾<p>Specialty tomato sauce, mozzarella cheese, tomatoes, basil</p></font>`,
    Felice: `<font size="3">Pizza Felice — 25 ₾<p>Specialty tomato sauce, mozzarella cheese, becon, pineapple</p></font>`,
    Vegeta: `<font size="3">Vegeta Pizza — 24 ₾<p>Specialty tomato sauce, mozzarella cheese, onion, tomatoes, sweet pepper, zucchini, champinoins, greens</p></font>`,
    Snacks: `Snacks`,
    CheeseSticks: `<font size="3">Cheese Sticks (5 pcs) — 15 ₾</font>`,
    Fishsticks: `<font size="3">Fish sticks — 14 ₾</font>`,
    Tigershrimp: `<font size="3">Tiger shrimp (6 pcs) — 13 ₾</font>`,
    Onionrings: `<font size="3">Onion rings — 10 ₾</font>`,
    Frenchfries: `<font size="3">French fries — 10 ₾</font>`,
    Rusticpotatoes: `<font size="3">Rustic potatoes — 10 ₾</font>`,
    Mexicanpotatoes: `<font size="3">Mexican potatoes — 10 ₾</font>`,
    Nuggets: `<font size="3">Nuggets — 9 ₾</font>`,
    Boiledshrimp: `<font size="3">Boiled shrimp 90/120 (10 pcs) — 9 ₾</font>`,
    Grill: 'Grill',
    Porkmedallions: `<font size="3">Pork medallions — 16 ₾</font>`,
    Chickenwings: `<font size="3">Chicken wings (3 pcs) — 16 ₾</font>`,
    Tilapiafish: `<font size="3">Tilapia fish — 14 ₾</font>`,
    Sausages: `<font size="3">Sausages (2 pcs) — 10 ₾</font>`,
    Shrimp: `<font size="3">Shrimp (1 pc) — 5-6 ₾</font>`,
    Salads: `Salads`,
    ShrimpCaesar: `<font size="3">Shrimp Caesar — 25 ₾</font>`,
    Caesarwithsmokedchicken: `<font size="3">Caesar with smoked chicken — 17 ₾</font>`,
    Greeksalad: `<font size="3">Greek salad with cottage cheese — 15 ₾</font>`,
    Vegetablesalad: `<font size="3">Vegetable salad — 9 ₾</font>`

  },
  ka: {
    bar48batumi: `Bar 48 - ბათუმი`,
    bar48batumiphotos: `ფოტო - Bar 48 - ბათუმი`,
    bar48batumidrink: `სასმელები - Bar 48 - ბათუმი`,
    bar48batumifood: `საკვები - Bar 48 - ბათუმი`,
    bar48: `Bar 48`,
    open: `ღიაა 00:30-დან 06:00-მდე`,
    address: `<a href="https://www.google.ge/maps/place/Bar+48/@41.6472818,41.6299166,17z/data=!4m6!3m5!1s0x4067877c6534400d:0x36e22db643766849!8m2!3d41.6474543!4d41.6323109!16s%2Fg%2F11rvh7wrxh&hl=ka" target="_blank">ბათუმი, 26 მაისის ქუჩა, №27</a>`,
    telegram: `<a href="https://t.me/BAR48_Batumi" target="_blank">ტელეგრამ ჯგუფი</a>`,
    offer: `🎉 სპეციალური შეთავაზება: ლუდის დეპოზიტი!`,
    offer2: `<strong>5 ჭიქა ლუდი — 20 ₾ </strong>(მოქმედებს ერთი სამუშაო ცვლის განმავლობაში)<br><strong>12 ჭიქა ლუდი — 50 ₾ </strong>(მოქმედებს 14 დღის განმავლობაში)<br><br>📲<i> ხელმისაწვდომია მხოლოდ ჩვენი <a href="https://t.me/BAR48_Batumi" target="_blank">Telegram</a> ჯგუფის წევრებისთვის.</i>`,
    welcome: `მოგესალმებით ჩვენს ბარში!`,
    great: `შესანიშნავი სასმელები და როკ-ბარის ატმოსფერო გელით ყოველ საღამოს. <b>„გულს ნუ სწუხარ? დალიე!“</b> — ეს ჩვენი დევიზია! დატკბი წამით და სასიამოვნო გარემოთი!`,
    photos: `<a href="/photos" class="button">ბარი ფოტოებში</a>`,
    drinks: `<a href="/drinks">სასმელები</a>`,
    food: `<a href="/food">საკვები</a>`,
    homestylepork: `ღორის ხორცი შინაურულად — 14 ₾`,
    beervodka: `ლუდი, არაყი, ჯინი, ვისკი და კოქტეილები ყველა გემოვნებისთვის. ჩვენთან ყველაფერია!<p>60-ზე მეტი სახეობის სიროფი და ლიკიორი</p>`,
    beer: `ბათუმური ლუდი (400 მლ) — 7 ₾<p>ყოველთვის ახალი, შესანიშნავი ლუდი პირდაპირ ბათუმის ლუდსახარშიდან</p>`,
    fulldrinks: `<a href="/drinks" class="button">სრული სასმელების მენიუ</a>`,
    fullfood: `<a href="/food" class="button">სრული კვების მენიუ</a>`,
    getdirections: `როგორ მივიდეთ`,
    map: `<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3545.564730481724!2d41.63337243995288!3d41.64596064402859!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4067877c6534400d%3A0x36e22db643766849!2z0JHQsNGAIDQ4!5e0!3m2!1ska!2sge!4v1701516762082!5m2!1ska!2sge" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade" title="googlemaps" data-i18n="map"></iframe>`,
    pleaseleaveareview: `დატოვე შეფასება`,
    beer1: `ლუდი`,
    home: `<a href="../" class="button">მთავარი</a>`,
    shots: `შოთები`,
    smoothies: `სმუზები`,
    cocktails: `კოქტეილები`,
    tequilaboom: `<font size="3">Tequila boom (40 მლ) — 8 ₾<p>ტეკილა, სპრაიტი</p></font>`,
    boyarasky: `<font size="3">ბოიარსკი (40 მლ) — 11 ₾<p>გრენადინის სიროფი, არაყი, ტაბასკო</p></font>`,
    valentinka: `<font size="3">ვალენტინკა (40 მლ) — 11 ₾<p>ავტორის შოთი</p></font>`,
    greenmexican: `<font size="3">Green mexican (40 მლ) — 13 ₾<p>საზამთროს ლიქიორი, ლიმონის წვენი, ტეკილა</p></font>`,
    bitterpill: `<font size="3">Bitter pill (40 მლ) — 13 ₾<p>მანგოს სიროფი, წითელი ვერმუტი, არაყი</p></font>`,
    arabica: `<font size="3">Arabica (40 მლ) — 13 ₾<p>გრენადინის სიროფი, ყავის ლიქიორი, ლიმონის წვენი, ტეკილა</p></font>`,
    b52: `<font size="3">ბ-52 (40 მლ) — 13 ₾<p>Kahlua ლიქიორი, Baileys ლიქიორი, Triple sec ლიქიორი</p></font>`,
    b53: `<font size="3">ბ-53 (40 მლ) — 13 ₾<p>Kahlua ლიქიორი, Baileys ლიქიორი, აბსენტი 70%</p></font>`,
    jellyfish: `<font size="3">Jellyfish (40 მლ) — 15 ₾<p>Malibu ლიქიორი, Triple sec ლიქიორი, Baileys ლიქიორი, Blue curacao ლიქიორი</p></font>`,
    hiroshima: `<font size="3">Hiroshima (40 მლ) — 15 ₾<p>Sambuka ლიქიორი, Baileys ლიქიორი, აბსენტი 70%, გრენადინის სიროფი</p></font>`,
    kamikadze: `<font size="3">Kamikadze (40 მლ) — 15 ₾<p>ავტორის შოთი</p></font>`,
    coldseabuckthorn: `<font size="3">Cold sea buckthorn (150 მლ) — 12 ₾<p>არაყი, ზღვის წვიტას პიურე, გრენადინის სიროფი, ლიმონის წვენი, ყინული</p></font>`,
    applecherry: `<font size="3">Apple-cherry (150 მლ) — 12 ₾<p>არაყი, ალუბლის პიურე, ვაშლის წვენი, ლიმონის წვენი, ყინული</p></font>`,
    blackmaple: `<font size="3">Black maple (150 მლ) — 12 ₾<p>არაყი, მოცვის პიურე, ნეკერჩხლის სიროფი, ლიმონის წვენი, ყინული</p></font>`,
    mexicanlime: `<font size="3">Mexican lime (150 მლ) — 17 ₾<p>ტეკილა, ლაიმის პიურე, ლიმონის წვენი, ყინული</p></font>`,
    icemango: `<font size="3">Ice mango (150 მლ) — 17 ₾<p>ტეკილა, მანგოს პიურე, ლიჩის სიროფი, ლიმონის წვენი, ყინული</p></font>`,
    cloverclubsmoothies: `<font size="3">Clover club smoothies (150 მლ) — 18 ₾<p>ჯინი, ჟოლოს პიურე, ლიმონის წვენი, ყინული</p></font>`,
    blueorange: `<font size="3">Blue orange (150 მლ) — 18 ₾<p>ჯინი, ლაიმის პიურე, Blue curacao სიროფი, ლიმონის წვენი, ყინული</p></font>`,
    antimojito: `<font size="3">Anti mojito (150 მლ) — 22 ₾<p>რომი, პიურე, ლაიმის-ლიმონის სიროფი, პიტნა, ლიმონის წვენი, ყინული</p></font>`,
    knickerbockersmoothie: `<font size="3">Knickerbocker smoothie (150 მლ) — 22 ₾<p>რომი, ჟოლოს პიურე, ფორთოხლის სიროფი, ლიმონის წვენი, ყინული</p></font>`,
    bluelagoon: `<font size="3">Blue lagoon (200 მლ) — 16 ₾<p>არაყი, Blue curacao ლიქიორი, სპრაიტი, ყინული</p></font>`,
    whiterussian: `<font size="3">White russian (150 მლ) — 17 ₾<p>არაყი, Kahlua ლიქიორი, ნაღები, ყინული</p></font>`,
    margarita: `<font size="3">Margarita (150 მლ) — 17 ₾<p>Olmeca ტეკილა, Triple sec ლიქიორი, შაქრის სიროფი, ლიმონის წვენი</p></font>`,
    gintonic: `<font size="3">Gin tonic (200 მლ) — 17 ₾<p>ჯინი, ტონიკი, ლიმონის წვენი, ყინული</p></font>`,
    tequilasunrise: `<font size="3">Tequila sunrise (200 მლ) — 18 ₾<p>Olmeca ტეკილა, ფორთოხლის წვენი, გრენადინის სიროფი, ყინული</p></font>`,
    irishcoffee: `<font size="3">Irish coffee (150 მლ) — 18 ₾<p>ირლანდიური ვისკი, შაქრის სიროფი, ყავა, ნაღები</p></font>`,
    cloverclub: `<font size="3">Clover club (150 მლ) — 18 ₾<p>ჯინი, ჟოლოს სიროფი, ლიმონის წვენი, ცილის ქაფი</p></font>`,
    whiskeysour: `<font size="3">Whiskey sour (150 მლ) — 18 ₾<p>Jameson ვისკი, შაქრის სიროფი, ლიმონის წვენი, ცილის ქაფი, ანგოსტურა, ყინული</p></font>`,
    bloodymary: `<font size="3">Bloody Mary (200 მლ) — 18 ₾<p>არაყი, ტომატის წვენი, სოიოს სოუსი, ტაბასკო, ვორესტერის სოუსი, მარილი, წიწაკა, ყინული</p></font>`,
    cubalibre: `<font size="3">Cuba-libre (200 მლ) — 18 ₾<p>რომი, კოლა, ლიმონის წვენი, ლიმონი, ყინული</p></font>`,
    french75: `<font size="3">French 75 (150 მლ) — 18 ₾<p>ჯინი, პროსეკო, შაქრის სიროფი, ლიმონის წვენი</p></font>`,
    negroni: `<font size="3">Negroni (100 მლ) — 19 ₾<p>ჯინი, Campari, Martini Rosso, ფორთოხლის ცედრა</p></font>`,
    daiquiri: `<font size="3">Daiquiri (150 მლ) — 19 ₾<p>თეთრი რომი, შაქრის სიროფი, ლიმონის წვენი, ლიმონი</p></font>`,
    aperolspritz: `<font size="3">Aperol spritz (150 მლ) — 19 ₾<p>Aperol, შამპანური, ტონიკი, ფორთოხალი</p></font>`,
    maitai: `<font size="3">Mai-tai (200 მლ) — 20 ₾<p>თეთრი რომი, მუქი რომი, Triple sec ლიქიორი, ნუშის სიროფი, შაქრის სიროფი, ლიმონის წვენი, ყინული</p></font>`,
    espressomartini: `<font size="3">Espresso martini (150 მლ) — 20 ₾<p>არაყი, ყავის ლიქიორი, ყავა, შაქრის სიროფი</p></font>`,
    sexonthebeach: `<font size="3">Sex on the beach (200 მლ) — 20 ₾<p>არაყი, ატმის ლიქიორი, მოცვის სიროფი, ანანასის წვენი, ლიმონის წვენი, ყინული</p></font>`,
    boulevardier: `<font size="3">Boulevardier (150 მლ) — 20 ₾<p>ვისკი, წითელი ვერმუტი, Campari, ფორთოხლის ცედრა, ყინული</p></font>`,
    pinacolada: `<font size="3">Pina-colada (250 მლ) — 25 ₾<p>თეთრი რომი, Malibu ლიქიორი, ანანასის წვენი, ქოქოსის სიროფი, ნაღები, ყინული</p></font>`,
    mojito: `<font size="3">Mojito (250 მლ) — 25 ₾<p>თეთრი რომი, სპრაიტი, Mojito სიროფი, ლიმონის წვენი, პიტნა, ლიმონი, ყინული</p></font>`,
    longisland: `<font size="3">Long island (250 მლ) — 25 ₾<p>არაყი, ტეკილა, ჯინი, რომი, Triple sec ლიქიორი, ლიმონის წვენი, კოლა / ცივი ჩაი, ყინული</p></font>`,
    pizza: `პიცა`,
    Carnea: `<font size="3">პიცა კარნეა — 40 ₾<p>სპეციალური პომიდვრის სოუსი, მოციარეალა ყველი, ხამი, ქათმის ფილე, უალბად მოხარშული ბეკონი, სალამის სოსისი, პომიდვრები, ხახვი</p></font>`,
    Suprim: `<font size="3">პიცა სუპრიმ — 32 ₾<p>სპეციალური პომიდვრის სოუსი, მოციარეალა ყველი, პეპერონის სოსისი, წიწაკის ბულბულები, ქათმის ფილე, ხახვი, სოკო, ზეთიანი</p></font>`,
    Bolognese: `<font size="3">პიცა ბოლონეზე — 31 ₾<p>სპეციალური პომიდვრის სოუსი, მოციარეალა ყველი, ბეკონი, ტყეპილი ხორცი, პომიდვრები, ხახვი, მწვანილები</p></font>`,
    Spicy: `<font size="3">პიცა სპაისი — 31 ₾<p>სპეციალური პომიდვრის სოუსი, მოციარეალა ყველი, დორბლუ ყველი, საქონლის ფილე, ბეკონი, სოკო, ცხელი წიწაკა</p></font>`,
    ShrimpPizza: `<font size="3">პიცა კრევეტებით — 31 ₾<p>ჩიზ-ნიორის სოუსი, მოციარეალა ყველი, კრევეტები, ზეთისხილი</p></font>`,
    Brooklyn: `<font size="3">ბრუკლინის პიცა — 33 ₾<p>სპეციალური პომიდვრის სოუსი, მოციარეალა ყველი, მოხარშული სოსისი, სალამის სოსისი, პეპერონის სოსისი, სოკო, კიბო</p></font>`,
    Diablo: `<font size="3">პიცა დიაბლო — 30 ₾<p>სპეციალური პომიდვრის სოუსი, მოციარეალა ყველი, ხამი, პეპერონის სოსისი, სოკო, ცხელი წიწაკა</p></font>`,
    FourCheesePizza: `<font size="3">პიცა ოთხი ყველით — 29 ₾<p>სპეციალური პომიდვრის სოუსი, მოციარეალა ყველი, დორბლუ ყველი, სულგუნი ყველი, პარმეზანის ყველი</p></font>`,
    Rustic: `<font size="3">რუსტიკ პიცა — 32 ₾<p>სპეციალური პომიდვრის სოუსი, მოციარეალა ყველი, საქონლის ფილე, მურაბა, პომიდვრები, მწვანილები</p></font>`,
    Hunter: `<font size="3">მჭადრაკელის პიცა — 28 ₾<p>სპეციალური პომიდვრის სოუსი, მოციარეალა ყველი, სანადირო სოსისი, სოკო, წიწაკის ბულბულები, ხახვი, პომიდვრები, ბეკონი, მწვანილები</p></font>`,
    Caesarpizza: `<font size="3">ცეზარის პიცა — 28 ₾<p>ცეზარის სოუსი, მოციარეალა ყველი, პარმეზანის ყველი, ქათამი, ბეკონი, აისბერგი სალათი, ჩერის პომიდვრები, კრუტონები</p></font>`,
    Pepperoni: `<font size="3">პეპერონის პიცა — 28 ₾<p>სპეციალური პომიდვრის სოუსი, მოციარეალა ყველი, პეპერონის სოსისი, წიწაკის ბულბულები, ზეთისხილი</p></font>`,
    Halal: `<font size="3">ჰალალ პიცა — 28 ₾<p>სპეციალური პომიდვრის სოუსი, მოციარეალა ყველი, საქონლის ხორცი, მდუმარი ქათამი, პომიდვრები, ხახვი</p></font>`,
    Goodmorning: `<font size="3">გუდ მორნინგ პიცა — 26 ₾<p>სპეციალური პომიდვრის სოუსი, მოციარეალა ყველი, ბეკონი, პომიდვრები, ქათმის კვერცხები, მწვანილები</p></font>`,
    Romana: `<font size="3">პიცა რომანა — 26 ₾<p>ზეთისხილის ზეთი, მოციარეალა ყველი, როკფორების ყველი, გოჭი</p></font>`,
    Carbonara: `<font size="3">პიცა კარბონარა — 26 ₾<p>სპეციალური პომიდვრის სოუსი, მოციარეალა ყველი, პარმეზანის ყველი, ქათმის კვერცხი, დაუხვეწავი ბეკონი, სალათის ფურცლები, პომიდვრები</p></font>`,
    Cippolino: `<font size="3">ჩიპოლინოს პიცა — 27 ₾<p>სპეციალური პომიდვრის სოუსი, მოციარეალა ყველი, ქათმის ფილე, მურაბა, წითელი ხახვი, ბასილი, მწვანილები</p></font>`,
    Julienne: `<font size="3">ჯულიენის პიცა — 28 ₾<p>კეფირის სოუსი, მოციარეალა ყველი, ქათმის ფილე, სოკო, ხახვი, მწვანილები</p></font>`,
    ClubPizza: `<font size="3">პიცა კლუბი — 26 ₾<p>სპეციალური პომიდვრის სოუსი, მოციარეალა ყველი, ხამი, პომიდვრები</p></font>`,
    Zeus: `<font size="3">ზევსის პიცა — 24 ₾<p>ზეთისხილის ზეთი, მოციარეალა ყველი, პომიდვრები, წიწაკა, ზეთისხილი, კიტრი, ქოტეჯის ყველი, წითელი ხახვი</p></font>`,
    Gallina: `<font size="3">პიცა გალინა — 26 ₾<p>სპეციალური პომიდვრის სოუსი, მოციარეალა ყველი, ქათმის ფილე</p></font>`,
    Mushroom: `<font size="3">სოკოს პიცა — 24 ₾<p>თეთრი სოუსი, მოციარეალა ყველი, სოკო, ხახვი, კიბო</p></font>`,
    TwoCheesePizza: `<font size="3">პიცა ორი ყველით — 22 ₾<p>სპეციალური პომიდვრის სოუსი, მოციარეალა ყველი, სულგუნი ყველი</p></font>`,
    Americana: `<font size="3">პიცა ამერიკანა — 32 ₾<p>სპეციალური პომიდვრის სოუსი, მოცარელას ყველი, ლორი, პეპერონის ძეხვი, სოკო</p></font>`,
    Hawaii: `<font size="3">პიცა ჰავაი — 27 ₾<p>სპეციალური პომიდვრის სოუსი, მოცარელას ყველი, ქათმის ფილე, ანანასი</p></font>`,
    Margarita: `<font size="3">პიცა მარგარიტა — 25 ₾<p>სპეციალური პომიდვრის სოუსი, მოცარელას ყველი, პომიდორი, ბაზილიკი</p></font>`,
    Felice: `<font size="3">პიცა ფელიჩე — 25 ₾<p>სპეციალური პომიდვრის სოუსი, მოცარელას ყველი, ბეკონი, ანანასი</p></font>`,
    Vegeta: `<font size="3">ვეგეტა პიცა — 24 ₾<p>სპეციალური პომიდვრის სოუსი, მოცარელას ყველი, ხახვი, პომიდორი, ბულგარული წიწაკა, ყაბაყი, შამპინიონები, მწვანილი</p></font>`,
    Snacks: `სნეკები`,
    CheeseSticks: `<font size="3">ჩიზ სტიქები (5 ცალი) — 15 ₾</font>`,
    Fishsticks: `<font size="3">თევზის სტიკები — 14 ₾</font>`,
    Tigershrimp: `<font size="3">ტაიგერის კრევეტები (6 ცალი) — 13 ₾</font>`,
    Onionrings: `<font size="3">სისელის რგოლები — 10 ₾</font>`,
    Frenchfries: `<font size="3">ფრანგული ფრიტსი — 10 ₾</font>`,
    Rusticpotatoes: `<font size="3">რუსტიკელი კარტოფილი — 10 ₾</font>`,
    Mexicanpotatoes: `<font size="3">მექსიკური კარტოფილი — 10 ₾</font>`,
    Nuggets: `<font size="3">ნაგეტები — 9 ₾</font>`,
    Boiledshrimp: `<font size="3">განთიებული კრევეტები 90/120 (10 ცალი) — 9 ₾</font>`,
    Grill: 'გრილი',
    Porkmedallions: `<font size="3">ღორის მედალიონები — 16 ₾</font>`,
    Chickenwings: `<font size="3">ქათმის ფრთები (3 ცალი) — 16 ₾</font>`,
    Tilapiafish: `<font size="3">თილაპია თევზი — 14 ₾</font>`,
    Sausages: `<font size="3">სოსისები (2 ცალი) — 10 ₾</font>`,
    Shrimp: `<font size="3">კრევეტი (1 ცალი) — 5-6 ₾</font>`,
    Salads: `სალათები`,
    ShrimpCaesar: `<font size="3">კრევეტების ცეზარი — 25 ₾</font>`,
    Caesarwithsmokedchicken: `<font size="3">ცეზარი მდუმარი ქათმით — 17 ₾</font>`,
    Greeksalad: `<font size="3">ბერძნული სალათი ქოტეჯის ყველით — 15 ₾</font>`,
    Vegetablesalad: `<font size="3">ბოსტნეულის სალათი — 9 ₾</font>`

  },
  ru: {
    bar48batumi: `Bar 48 - Батуми`,
    bar48batumiphotos: `Фото - Bar 48 - Батуми`,
    bar48batumidrink: `Напитки - Bar 48 - Батуми`,
    bar48batumifood: `Еда - Bar 48 - Батуми`,
    bar48: `Bar 48`,
    open: `Открыто с 00:30 до 06:00`,
    address: `<a href="https://www.google.ru/maps/place/Bar+48/@41.6472818,41.6299166,17z/data=!4m6!3m5!1s0x4067877c6534400d:0x36e22db643766849!8m2!3d41.6474543!4d41.6323109!16s%2Fg%2F11rvh7wrxh&hl=ru" target="_blank">Батуми, ул. 26 Мая, д.27</a>`,
    telegram: `<a href="https://t.me/BAR48_Batumi" target="_blank">Группа в Telegram</a>`,
    offer: `🎉 Специальное предложение: Пивной депозит!`,
    offer2: `<strong>5 бокалов пива — 20 ₾ </strong>(действует в течение одной рабочей смены)<br><strong>12 бокалов пива — 50 ₾ </strong>(действует в течение 14 дней)<br><br>📲<i> Доступно только для участников нашей группы в <a href="https://t.me/BAR48_Batumi" target="_blank">Telegram</a>.</i>`,
    welcome: `Добро пожаловать в наш бар!`,
    great: `Отличные напитки и атмосфера рок-бара ждут вас каждый вечер. <b>«Приуныл? Прибухни!»</b> — наш девиз! Наслаждайся моментом и приятной компанией!`,
    photos: `<a href="/photos" class="button">Бар в фотографиях</a>`,
    drinks: `<a href="/drinks">Напитки</a>`,
    food: `<a href="/food">Еда</a>`,
    homestylepork: `Свинина по-домашнему — 14 ₾`,
    beervodka: `Пиво, водка, джин, виски и коктейли на любой вкус. У нас есть всё!<p>Более 60 видов сиропов и ликёров</p>`,
    beer: `Батумское пиво (400 мл) — 7 ₾<p>Всегда свежее, отличное пиво прямо с батумского пивзавода</p>`,
    fulldrinks: `<a href="/drinks" class="button">Полное меню напитков</a>`,
    fullfood: `<a href="/food" class="button">Полное меню еды</a>`,
    getdirections: `Как добраться`,
    map: `<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3545.564730481724!2d41.63337243995288!3d41.64596064402859!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4067877c6534400d%3A0x36e22db643766849!2z0JHQsNGAIDQ4!5e0!3m2!1sru!2sru!4v1701516762082!5m2!1sru!2sru" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade" title="googlemaps" data-i18n="map"></iframe>`,
    pleaseleaveareview: `Пожалуйста, оставьте отзыв`,
    home: `<a href="../" class="button">На главную</a>`,
    beer1: `Пиво`,
    shots: `Шоты`,
    smoothies: `Смузи`,
    cocktails: `Коктейли`,
    tequilaboom: `<font size="3">Tequila boom (40 мл) — 8 ₾<p>Текила, спрайт</p></font>`,
    boyarasky: `<font size="3">Боярский (40 мл) — 11 ₾<p>Сироп гренадина, водка, табаско</p></font>`,
    valentinka: `<font size="3">Валентинка (40 мл) — 11 ₾<p>Авторский шот</p></font>`,
    greenmexican: `<font size="3">Зелёный мексиканец (40 мл) — 13 ₾<p>Дынный ликёр, лимонный сок, текила</p></font>`,
    bitterpill: `<font size="3">Горькая пилюля (40 мл) — 13 ₾<p>Манговый сироп, красный вермут, водка</p></font>`,
    arabica: `<font size="3">Arabica (40 мл) — 13 ₾<p>Сироп гренадина, кофейный ликёр, лимонный сок, текила</p></font>`,
    b52: `<font size="3">Б-52 (40 мл) — 13 ₾<p>Ликёр калуа, ликёр бейлис, трипл сек</p></font>`,
    b53: `<font size="3">Б-53 (40 мл) — 13 ₾<p>Ликёр калуа, ликёр бейлис, абсент 70%</p></font>`,
    jellyfish: `<font size="3">Медуза (40 мл) — 15 ₾<p>Ликёр малибу, трипл сек, бейлис, блю кюрасао</p></font>`,
    hiroshima: `<font size="3">Hiroshima (40 мл) — 15 ₾<p>Самбука, бейлис, абсент 70%, сироп гренадина</p></font>`,
    kamikadze: `<font size="3">Kamikadze (40 мл) — 15 ₾<p>Авторский шот</p></font>`,
    coldseabuckthorn: `<font size="3">Холодная облепиха (150 мл) — 12 ₾<p>Водка, облепиховое пюре, сироп гренадина, лимонный сок, лёд</p></font>`,
    applecherry: `<font size="3">Apple-cherry (150 мл) — 12 ₾<p>Водка, вишнёвое пюре, яблочный сок, лимонный сок, лёд</p></font>`,
    blackmaple: `<font size="3">Чёрный клён (150 мл) — 12 ₾<p>Водка, черничное пюре, кленовый сироп, лимонный сок, лёд</p></font>`,
    mexicanlime: `<font size="3">Мексиканский лайм (150 мл) — 17 ₾<p>Текила, лаймовое пюре, лимонный сок, лёд</p></font>`,
    icemango: `<font size="3">Ice mango (150 мл) — 17 ₾<p>Текила, манговое пюре, сироп личи, лимонный сок, лёд</p></font>`,
    cloverclubsmoothies: `<font size="3">Clover club smoothies (150 мл) — 18 ₾<p>Джин, малиновое пюре, лимонный сок, лёд</p></font>`,
    blueorange: `<font size="3">Blue orange (150 мл) — 18 ₾<p>Джин, лаймовое пюре, сироп блю кюрасао, лимонный сок, лёд</p></font>`,
    antimojito: `<font size="3">Anti mojito (150 мл) — 22 ₾<p>Ром, лаймовое пюре, лайм-лимонный сироп, мята, лимонный сок, лёд</p></font>`,
    knickerbockersmoothie: `<font size="3">Knickerbocker smoothie (150 мл) — 22 ₾<p>Ром, малиновое пюре, апельсиновый сироп, лимонный сок, лёд</p></font>`,
    bluelagoon: `<font size="3">Blue lagoon (200 мл) — 16 ₾<p>Водка, ликёр блю кюрасао, спрайт, лёд</p></font>`,
    whiterussian: `<font size="3">White russian (150 мл) — 17 ₾<p>Водка, Калуа, сливки, лёд</p></font>`,
    margarita: `<font size="3">Margarita (150 мл) — 17 ₾<p>Текила Olmeca, трипл сек, сахарный сироп, лимонный сок</p></font>`,
    gintonic: `<font size="3">Gin tonic (200 мл) — 17 ₾<p>Джин, тоник, лимонный сок, лёд</p></font>`,
    tequilasunrise: `<font size="3">Tequila sunrise (200 мл) — 18 ₾<p>Текила Olmeca, апельсиновый сок, сироп гренадина, лёд</p></font>`,
    irishcoffee: `<font size="3">Irish coffee (150 мл) — 18 ₾<p>Ирландский виски, сахарный сироп, кофе, взбитые сливки</p></font>`,
    cloverclub: `<font size="3">Clover club (150 мл) — 18 ₾<p>Джин, малиновый сироп, лимонный сок, белок</p></font>`,
    whiskeysour: `<font size="3">Whiskey sour (150 мл) — 18 ₾<p>Виски Jameson, сахарный сироп, лимонный сок, белок, ангостура, лёд</p></font>`,
    bloodymary: `<font size="3">Bloody Mary (200 мл) — 18 ₾<p>Водка, томатный сок, соевый соус, табаско, вустер, соль, перец, лёд</p></font>`,
    cubalibre: `<font size="3">Cuba-libre (200 мл) — 18 ₾<p>Ром, кола, лимонный сок, лимон, лёд</p></font>`,
    french75: `<font size="3">French 75 (150 мл) — 18 ₾<p>Джин, просекко, сахарный сироп, лимонный сок</p></font>`,
    negroni: `<font size="3">Negroni (100 мл) — 19 ₾<p>Джин, кампари, мартини россо, апельсиновая цедра</p></font>`,
    daiquiri: `<font size="3">Daiquiri (150 мл) — 19 ₾<p>Белый ром, сахарный сироп, лимонный сок, лимон</p></font>`,
    aperolspritz: `<font size="3">Aperol spritz (150 мл) — 19 ₾<p>Апероль, шампанское, тоник, апельсин</p></font>`,
    maitai: `<font size="3">Mai-tai (200 мл) — 20 ₾<p>Белый ром, тёмный ром, трипл сек, миндальный сироп, сахарный сироп, лимонный сок, лёд</p></font>`,
    espressomartini: `<font size="3">Espresso martini (150 мл) — 20 ₾<p>Водка, кофейный ликёр, кофе, сахарный сироп</p></font>`,
    sexonthebeach: `<font size="3">Sex on the beach (200 мл) — 20 ₾<p>Водка, персиковый ликёр, клюквенный сироп, ананасовый сок, лимонный сок, лёд</p></font>`,
    boulevardier: `<font size="3">Boulevardier (150 мл) — 20 ₾<p>Виски, красный вермут, кампари, апельсиновая цедра, лёд</p></font>`,
    pinacolada: `<font size="3">Pina-colada (250 мл) — 25 ₾<p>Белый ром, ликёр малибу, ананасовый сок, кокосовый сироп, сливки, лёд</p></font>`,
    mojito: `<font size="3">Mojito (250 мл) — 25 ₾<p>Белый ром, спрайт, мохито сироп, лимонный сок, мята, лимон, лёд</p></font>`,
    longisland: `<font size="3">Long island (250 мл) — 25 ₾<p>Водка, текила, джин, ром, трипл сек, лимонный сок, кола / айс-ти, лёд</p></font>`,
    pizza: `Пицца`,
    Carnea: `<font size="3">Пицца Карнеа — 40 ₾<p>Фирменный томатный соус, сыр моцарелла, ветчина, куриное филе, сырокопченый бекон, колбаса салями, помидоры, лук</p></font>`,
    Suprim: `<font size="3">Пицца Суприм — 32 ₾<p>Фирменный томатный соус, сыр моцарелла, колбаса пепперони, болгарский перец, куриное филе, лук, грибы, оливки</p></font>`,
    Bolognese: `<font size="3">Пицца Болоньезе — 31 ₾<p>Фирменный томатный соус, сыр моцарелла, бекон, фарш, помидоры, лук, зелень</p></font>`,
    Spicy: `<font size="3">Острая пицца — 31 ₾<p>Фирменный томатный соус, сыр моцарелла, сыр дорблю, говяжья вырезка, бекон, грибы, острый перец чили</p></font>`,
    ShrimpPizza: `<font size="3">Пицца с креветками — 31 ₾<p>Сырно-чесночный соус, сыр моцарелла, креветки, оливки</p></font>`,
    Brooklyn: `<font size="3">Пицца Бруклинская — 33 ₾<p>Фирменный томатный соус, моцарелла, вареная колбаса, салями, колбаса пепперони, грибы, укроп</p></font>`,
    Diablo: `<font size="3">Пицца Диабло — 30 ₾<p>Фирменный томатный соус, сыр моцарелла, ветчина, колбаса пепперони, грибы, острый перец чили</p></font>`,
    FourCheesePizza: `<font size="3">Пицца Четыре Сыра — 29 ₾<p>Фирменный томатный соус, сыр моцарелла, сыр дорблю, сыр сулугуни, сыр пармезан</p></font>`,
    Rustic: `<font size="3">Деревенская пицца — 32 ₾<p>Фирменный томатный соус, сыр моцарелла, говяжья вырезка, корнишоны, помидоры, зелень</p></font>`,
    Hunter: `<font size="3">Охотничья пицца — 28 ₾<p>Фирменный томатный соус, сыр моцарелла, охотничьи колбаски, грибы, болгарский перец, лук, помидоры, бекон, зелень</p></font>`,
    Caesarpizza: `<font size="3">Пицца Цезарь — 28 ₾<p>Соус Цезарь, сыр моцарелла, сыр пармезан, курица, бекон, салат айсберг, помидоры черри, гренки</p></font>`,
    Pepperoni: `<font size="3">Пицца Пепперони — 28 ₾<p>Фирменный томатный соус, сыр моцарелла, колбаса пепперони, болгарский перец, оливки</p></font>`,
    Halal: `<font size="3">Халяльная пицца — 28 ₾<p>Фирменный томатный соус, сыр моцарелла, говядина, копченая курица, помидоры, лук</p></font>`,
    Goodmorning: `<font size="3">Пицца Доброе Утро — 26 ₾<p>Фирменный томатный соус, сыр моцарелла, бекон, помидоры, куриные яйца, зелень</p></font>`,
    Romana: `<font size="3">Римская пицца — 26 ₾<p>Оливковое масло, сыр моцарелла, сыр Рокфор, груша</p></font>`,
    Carbonara: `<font size="3">Пицца Карбонара — 26 ₾<p>Фирменный томатный соус, сыр моцарелла, сыр пармезан, куриное яйцо, сырокопченый бекон, салат, помидоры</p></font>`,
    Cippolino: `<font size="3">Пицца Чиполлино — 27 ₾<p>Фирменный томатный соус, сыр моцарелла, куриное филе, корнишоны, красный лук, базилик, зелень</p></font>`,
    Julienne: `<font size="3">Пицца Жульен — 28 ₾<p>Сметанный соус, сыр моцарелла, куриное филе, грибы, лук, зелень</p></font>`,
    ClubPizza: `<font size="3">Пицца Клаб — 26 ₾<p>Фирменный томатный соус, сыр моцарелла, ветчина, помидоры</p></font>`,
    Zeus: `<font size="3">Пицца Зевс — 24 ₾<p>Оливковое масло, сыр моцарелла, помидоры, болгарский перец, оливки, огурец, творог, красный лук</p></font>`,
    Gallina: `<font size="3">Пицца Галлина — 26 ₾<p>Фирменный томатный соус, сыр моцарелла, куриное филе</p></font>`,
    Mushroom: `<font size="3">Пицца с грибами — 24 ₾<p>Белый соус, сыр моцарелла, грибы, лук, укроп</p></font>`,
    TwoCheesePizza: `<font size="3">Пицца Два Сыра — 22 ₾<p>Фирменный томатный соус, сыр моцарелла, сыр сулгуни</p></font>`,
    Americana: `<font size="3">Пицца Американа — 32 ₾<p>Фирменный томатный соус, сыр моцарелла, ветчина, колбаса пепперони, грибы</p></font>`,
    Hawaii: `<font size="3">Гавайская пицца — 27 ₾<p>Фирменный томатный соус, сыр моцарелла, куриное филе, ананас</p></font>`,
    Margarita: `<font size="3">Пицца Маргарита — 25 ₾<p>Фирменный томатный соус, сыр моцарелла, помидоры, базилик</p></font>`,
    Felice: `<font size="3">Пицца Феличе — 25 ₾<p>Фирменный томатный соус, сыр моцарелла, бекон, ананас</p></font>`,
    Vegeta: `<font size="3">Пицца Вегета — 24 ₾<p>Фирменный томатный соус, сыр моцарелла, лук, помидоры, сладкий перец, кабачок, шампиньоны, зелень</p></font>`,
    Snacks: `Закуски`,
    CheeseSticks: `<font size="3">Сырные палочки (5 шт) — 15 ₾</font>`,
    Fishsticks: `<font size="3">Рыбные палочки — 14 ₾</font>`,
    Tigershrimp: `<font size="3">Тигровые креветки (6 шт) — 13 ₾</font>`,
    Onionrings: `<font size="3">Луковые кольца — 10 ₾</font>`,
    Frenchfries: `<font size="3">Картошка фри — 10 ₾</font>`,
    Rusticpotatoes: `<font size="3">Картошка по-деревенски — 10 ₾</font>`,
    Mexicanpotatoes: `<font size="3">Картошка по-мексикански — 10 ₾</font>`,
    Nuggets: `<font size="3">Наггетсы — 9 ₾</font>`,
    Boiledshrimp: `<font size="3">Вареные креветки 90/120 (10 шт) — 9 ₾</font>`,
    Grill: 'Гриль',
    Porkmedallions: `<font size="3">Свиные медальоны — 16 ₾</font>`,
    Chickenwings: `<font size="3">Куриные крылья (3 шт) — 16 ₾</font>`,
    Tilapiafish: `<font size="3">Рыба тилапия — 14 ₾</font>`,
    Sausages: `<font size="3">Сосиски (2 шт) — 10 ₾</font>`,
    Shrimp: `<font size="3">Креветка (1 шт) — 5-6 ₾</font>`,
    Salads: `Салаты`,
    ShrimpCaesar: `<font size="3">Цезарь с креветкой — 25 ₾</font>`,
    Caesarwithsmokedchicken: `<font size="3">Цезарь с копченой курицей — 17 ₾</font>`,
    Greeksalad: `<font size="3">Греческий салат с творогом — 15 ₾</font>`,
    Vegetablesalad: `<font size="3">Овощной салат — 9 ₾</font>`
  }
};

function setLanguage(lang) {
  localStorage.setItem('language', lang);
  updateText(lang);
}

function updateText(lang) {
  const elements = document.querySelectorAll("[data-i18n]");
  elements.forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (translations[lang] && translations[lang][key]) {
      el.innerHTML = translations[lang][key];
    }
  });
  document.getElementById("map").innerHTML = translations[lang].map;
}

function initLang() {
  const lang = localStorage.getItem('language') || 'en';
  updateText(lang);
}
  document.addEventListener("DOMContentLoaded", initLang);
